### ISSUE TITLE
Completed module 3 assignments

### ISSUE THREAD

**Issue by lasmacdonald** [ds4owd-001/md-03-assignments-lasmacdonald#1]
@larnsce @sskorik01 @mianzg

**Comment by lasmacdonald** [comment]
I've realized now that I missed doing md-03b-sanitation-visualise.qmd - will do today. Apologies.

**Comment by lasmacdonald** [comment]
Okay, officially finished. Apologies again for the delay!

**Comment by sskorik01** [comment]
No worries, it looks good. Well done 💯
